name: Web App CICD

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
  
permissions: write-all

jobs:
  build_test_deploy:

    name: Build Test and Deploy
    uses: ORT-DevOps-2023S2G1/workflows-repository/.github/workflows/react-app-cicd.yml@main
    secrets: inherit
